name: Build Image

on:
workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: setup qemu
        uses: docker/setup-qemu-action@v2
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: IMAGE_TAG=$(date -u +%Y%m%dT%H%M%S) make docker-push